### ISSUE TITLE
Issue after project creation

### ISSUE THREAD

**Issue by rmnbrd** [ZolaApp/zola-app#116]
<img width="457" alt="screenshot 2018-05-30 12 02 11" src="https://user-images.githubusercontent.com/426749/40713854-4ebb789c-6401-11e8-91bb-61258a694df0.png">

#### Expected behavior
Project creation success callback should correctly close the modal

**Comment by Tom-Bonnike** [comment]
I think it should work the second time you press.
That’s because you pass `this.dialog` which is undefined until the ref kicks in (on second re-render)
