### ISSUE TITLE
Add CSS reset

### ISSUE THREAD

**Issue by Tom-Bonnike** [ZolaApp/zola-app#4]

**Comment by Tom-Bonnike** [comment]
We’ll need to follow the doc here: https://github.com/zeit/next.js/wiki/Global-styles-and-layouts.

Let’s do that when we setup our styling system. If we go with styled components (why not), here’s an example: https://github.com/zeit/next.js/tree/canary/examples/with-styled-components.
It overrides `_document.js`, which is a nice way to have a place to add global styles :)

**Comment by rmnbrd** [comment]
Done ✅ 
https://github.com/ZolaApp/zola-app/pull/37
